import { VStack, Image } from '@chakra-ui/react'
import axios from 'axios';
import Head from 'next/head'
import { useState, useEffect } from 'react';

interface BeerProps {
   id: number,
  name: string,
  description: string,
  note: number,
  ibu: number,
  review: string,
  style:string,
  birthDay: string
}

const Index  = ({id, name, description, note, birthDay, ibu,review }:BeerProps)=>{
	const [response, setResponse] = useState(null);
  const [peopleDetail, setPeopleDetail] = useState({id, name, description, note, birthDay, ibu,review })
	const fetchQuotes = async () => {
		try {
			const res = await axios.get('http://localhost:3000/api/beers/clg5thfwm00061jeqel52lmdf');
			setResponse(res.data);
      setPeopleDetail(res.data)
      console.log(res.data)
		} catch (err) {
			console.log(err);
		}
	};
	useEffect(() => {
		// Trigger the API Call
		fetchQuotes();
	}, []);
	  return (
    <VStack>
      <Head>
        <title>Beers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     
  
      <div className="w-auto min-w-[25%] max-w-min mt-10 mx-auto space-y-6 flex flex-col items-stretch">
         <h1 className="text-center font-bold text-2xl m-4">Details:</h1>
        <ul>
            <li key={peopleDetail.id } className="border-b border-gray-600 p-2">
              <div className="flex jusify-between">
                <div className="flex-1">
                  <h3 className="font-bold">{peopleDetail.name}</h3>
                  <p className="text-sm">{peopleDetail.description}</p>
                  <p className="text-sm">Produced since :{peopleDetail.birthDay}</p>
                  <p className="text-sm">IBU: {peopleDetail.ibu}</p>
                  <p className="text-sm">Note: {peopleDetail.note}</p>
                  <p className="text-sm">Review: {peopleDetail.review}</p>
                </div>
              </div>
            </li>
        </ul>
      </div>
      </VStack>
  )
}

export default Index