import { StarIcon, InfoIcon, HamburgerIcon, ChatIcon } from '@chakra-ui/icons';
import { VStack, Text, Tabs, Tab, TabPanel, TabPanels, TabList, Image, Badge, Box, Flex, ListItem, List, Heading, HStack } from '@chakra-ui/react'
import axios from 'axios';
import Head from 'next/head'
import { useState, useEffect } from 'react';

interface BeerProps {
  id: number,
  name: string,
  description: string,
  note: number,
  ibu: number,
  review: string,
  style: string,
  birthDay: string
}

const Index = ({ id, name, description, note, birthDay, ibu, review }: BeerProps) => {
  const [response, setResponse] = useState(null);
  const [peopleDetail, setPeopleDetail] = useState({ id, name, description, note, birthDay, ibu, review })
  const fetchQuotes = async () => {
    try {
      const res = await axios.get('http://localhost:3000/api/beers/clg5k8l0f0002mwpbumqexd9k');
      setResponse(res.data);
      setPeopleDetail(res.data)
      console.log(res.data)
    } catch (err) {
      console.log(err);
    }
  };
  useEffect(() => {
    // Trigger the API Call
    fetchQuotes();
  }, []);
  return (
    <VStack>
      <Head>
        <title>Beers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



      <Flex
        direction={'column'}
        justifyContent={'center'}
        alignItems={'center'}
        w='full'
        h='full'
      >
        <Heading
          textTransform={'uppercase'}
          color={'green.600'}
        >
          {peopleDetail.name}
        </Heading >

        <Box as='main'
          display={'flex'}
          flexDirection={'column'}
          borderWidth='1px'
          borderRadius='lg'
          overflow='hidden'
          justifyContent={'center'}
          alignItems={'center'}
          width={'full'}
          paddingBottom={20}
        >
          <Image
            src={"https://www.heineken.com/media-la/01pfxdqq/heineken-original-bottle.png?anchor=center&mode=crop&width=570&height=854&quality=85"}
            alt={peopleDetail.name}
            width={"10vw"}
          />
          <Badge
            borderRadius='full'
            px='4'
            colorScheme='teal'
            mt={2}
          >
            Premium Lager
          </Badge>
          <HStack justifyContent={'center'} display={'flex'} mt={2} w='full'>
            {Array(10)
              .fill('')
              .map((_, i) => (
                <StarIcon
                  key={i}
                  width={'3'}
                  color={i < peopleDetail.note ? 'green.700' : 'blackAlpha.500'}
                />
              ))}
          </HStack>
          <VStack flexDirection={'column'} width={'100%'} display={'flex'} justifyContent={'flex-start'}>
            <Box display='flex' mt='2'>
              {peopleDetail.note}/10

            </Box>
            <Box as='span' color='gray.900' fontSize='sm'>
              IBU: {peopleDetail.ibu}
            </Box>
          </VStack>
          <Tabs
            borderColor={'gray.300'}
            w={'full'}
            isLazy
            mt={5}
            colorScheme='green'
            color={'gray.500'}
          >

            <TabList
              display={'flex'}
              justifyContent={'center'}
              alignItems={'center'}
            >
              <Tab >
                <HamburgerIcon mr={2} />História
              </Tab>
              <Tab>
                <ChatIcon mr={2} />Análises
              </Tab>
            </TabList>
            <TabPanels>
              <TabPanel
                display={'flex'}
                justifyContent={'center'}
                alignItems={'center'}>
                <Box
                  mt={5}
                  display={'flex'}
                  w={'60vw'}
                  textAlign={'justify'}
                  color={'gray.900'}
                  justifyContent={'center'}
                  maxW={500}
                >
                  {peopleDetail.description}
                </Box>
              </TabPanel>
              <TabPanel
                display={'flex'}
                justifyContent={'center'}
                alignItems={'center'}
              >
                <Box mt={5}
                  display={'flex'}
                  w={'60vw'}
                  textAlign={'justify'}
                  color={'gray.900'}
                  maxW={500}>
                  Análise: {peopleDetail.review}
                </Box>
              </TabPanel>
            </TabPanels>
          </Tabs>
        </Box>
      </Flex>
    </VStack>
  )
}

export default Index